// <auto-generated />
using System;
using LMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.API.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("bit");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Submit your Unity project",
                            DueDate = new DateTime(2026, 5, 16, 23, 59, 0, 0, DateTimeKind.Utc),
                            IsGraded = true,
                            SessionId = 12,
                            Title = "Session Assignment"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Week 11 session 2 assignment",
                            DueDate = new DateTime(2026, 3, 14, 23, 59, 0, 0, DateTimeKind.Utc),
                            IsGraded = true,
                            SessionId = 9,
                            Title = "Week 11 Assignment"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research freelancing platforms",
                            DueDate = new DateTime(2026, 3, 17, 23, 59, 0, 0, DateTimeKind.Utc),
                            IsGraded = false,
                            SessionId = 7,
                            Title = "Free Lancing Platforms Assignment"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.AssignmentSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("GradeFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("AssignmentSubmissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentId = 1,
                            FileUrl = "https://drive.google.com/file/1",
                            StudentId = 14,
                            SubmissionType = "file",
                            SubmittedAt = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssignmentId = 1,
                            FileUrl = "https://drive.google.com/file/2",
                            StudentId = 15,
                            SubmissionType = "file",
                            SubmittedAt = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignmentId = 1,
                            FileUrl = "https://drive.google.com/file/3",
                            StudentId = 16,
                            SubmissionType = "file",
                            SubmittedAt = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssignmentId = 2,
                            FileUrl = "https://drive.google.com/file/4",
                            StudentId = 14,
                            SubmissionType = "file",
                            SubmittedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AssignmentId = 2,
                            FileUrl = "https://drive.google.com/file/5",
                            StudentId = 15,
                            SubmissionType = "file",
                            SubmittedAt = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Joined")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 11, 29, 13, 5, 0, 0, DateTimeKind.Utc),
                            SessionId = 1,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 2,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 11, 29, 13, 10, 0, 0, DateTimeKind.Utc),
                            SessionId = 1,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 3,
                            Joined = false,
                            SessionId = 1,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 4,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 12, 1, 18, 2, 0, 0, DateTimeKind.Utc),
                            SessionId = 2,
                            StudentId = 14
                        },
                        new
                        {
                            Id = 5,
                            Joined = false,
                            SessionId = 2,
                            StudentId = 15
                        },
                        new
                        {
                            Id = 6,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 12, 1, 18, 15, 0, 0, DateTimeKind.Utc),
                            SessionId = 2,
                            StudentId = 16
                        },
                        new
                        {
                            Id = 7,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 12, 6, 14, 3, 0, 0, DateTimeKind.Utc),
                            SessionId = 5,
                            StudentId = 9
                        },
                        new
                        {
                            Id = 8,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 12, 6, 18, 1, 0, 0, DateTimeKind.Utc),
                            SessionId = 6,
                            StudentId = 10
                        },
                        new
                        {
                            Id = 9,
                            Joined = false,
                            SessionId = 6,
                            StudentId = 11
                        },
                        new
                        {
                            Id = 10,
                            Joined = true,
                            JoinedAt = new DateTime(2025, 12, 6, 18, 5, 0, 0, DateTimeKind.Utc),
                            SessionId = 6,
                            StudentId = 12
                        });
                });

            modelBuilder.Entity("LMS.API.Models.CoordinatorGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("CoordinatorGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoordinatorId = 2,
                            GroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoordinatorId = 2,
                            GroupId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoordinatorId = 2,
                            GroupId = 3
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CoordinatorId = 3,
                            GroupId = 4
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CAI4_AIS3_S2",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CAI4_AIS3_S2",
                            StartDate = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "GIZ4_DRT5_G1",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "GIZ4_DRT5_G1",
                            StartDate = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "GIZ4_DRT5_S1",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "GIZ4_DRT5_S1",
                            StartDate = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Code = "ONL4_DRT6_S1",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ONL4_DRT6_S1",
                            StartDate = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Senior Full-Stack Instructor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alaaelawady50@gmail.com",
                            IsActive = true,
                            Name = "Alaa Elawady",
                            Phone = "01011112222"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Soft Skills Trainer",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emad.instructor@lms.com",
                            IsActive = true,
                            Name = "Emad Eletreby",
                            Phone = "01022223333"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Backend & Cloud Instructor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "polakamal@hotmail.com",
                            IsActive = true,
                            Name = "Pola Zaki",
                            Phone = "01033334444"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Frontend Instructor",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hatem.heshmat@gmail.com",
                            IsActive = true,
                            Name = "Hatem Heshmat",
                            Phone = "01044445555"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "DevOps & Infrastructure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mostafa.instructor@lms.com",
                            IsActive = true,
                            Name = "Mostafa Ayman",
                            Phone = "01055556666"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("bit");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 5, 14, 23, 59, 0, 0, DateTimeKind.Utc),
                            IsGraded = true,
                            SessionId = 12,
                            Title = "Unity Basics Quiz",
                            Type = "multiple_choice"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "A",
                            OptionA = "A game engine",
                            OptionB = "A programming language",
                            OptionC = "A database",
                            OptionD = "An OS",
                            Order = 1,
                            Points = 2,
                            QuestionText = "What is Unity?",
                            QuizId = 1
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "C",
                            OptionA = "Java",
                            OptionB = "Python",
                            OptionC = "C#",
                            OptionD = "C++",
                            Order = 2,
                            Points = 2,
                            QuestionText = "Which language does Unity primarily use?",
                            QuizId = 1
                        });
                });

            modelBuilder.Entity("LMS.API.Models.QuizSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizSubmissions");
                });

            modelBuilder.Entity("LMS.API.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AttendanceTakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AttendanceTakenById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EndedById")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StartedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceTakenById");

                    b.HasIndex("EndedById");

                    b.HasIndex("GroupId");

                    b.HasIndex("StartedById");

                    b.HasIndex("TrainerId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceTakenAt = new DateTime(2025, 11, 29, 15, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 11, 29, 15, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 1 - session 1",
                            RecordLink = "https://zoom.us/rec/1",
                            SessionDate = new DateTime(2025, 11, 29, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 11, 29, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "live"
                        },
                        new
                        {
                            Id = 2,
                            AttendanceTakenAt = new DateTime(2025, 12, 1, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 1 - session 3",
                            RecordLink = "https://zoom.us/rec/2",
                            SessionDate = new DateTime(2025, 12, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 1, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "soft skill",
                            TrainerId = 2,
                            Type = "live"
                        },
                        new
                        {
                            Id = 3,
                            AttendanceTakenAt = new DateTime(2025, 12, 2, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 1 - session 2",
                            RecordLink = "https://zoom.us/rec/3",
                            SessionDate = new DateTime(2025, 12, 2, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 2, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "live"
                        },
                        new
                        {
                            Id = 4,
                            AttendanceTakenAt = new DateTime(2025, 12, 6, 15, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Location = "Cairo Hub, Room 201",
                            Name = "week 2 - session 1",
                            SessionDate = new DateTime(2025, 12, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "physical"
                        },
                        new
                        {
                            Id = 5,
                            AttendanceTakenAt = new DateTime(2025, 12, 6, 16, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 2,
                            Name = "week 1 - session 1",
                            RecordLink = "https://zoom.us/rec/5",
                            SessionDate = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 3,
                            Type = "live"
                        },
                        new
                        {
                            Id = 6,
                            AttendanceTakenAt = new DateTime(2025, 12, 6, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 6, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 3,
                            Name = "week 1 - session 1",
                            RecordLink = "https://zoom.us/rec/6",
                            SessionDate = new DateTime(2025, 12, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 6, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 4,
                            Type = "live"
                        },
                        new
                        {
                            Id = 7,
                            AttendanceTakenAt = new DateTime(2025, 12, 8, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 2 - session 3",
                            RecordLink = "https://zoom.us/rec/7",
                            SessionDate = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "soft skill",
                            TrainerId = 2,
                            Type = "live"
                        },
                        new
                        {
                            Id = 8,
                            AttendanceTakenAt = new DateTime(2025, 12, 8, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 8, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 2,
                            Name = "week 1 - session 2",
                            RecordLink = "https://zoom.us/rec/8",
                            SessionDate = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 3,
                            Type = "live"
                        },
                        new
                        {
                            Id = 9,
                            AttendanceTakenAt = new DateTime(2025, 12, 9, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 9, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 2 - session 2",
                            RecordLink = "https://zoom.us/rec/9",
                            SessionDate = new DateTime(2025, 12, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 9, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "live"
                        },
                        new
                        {
                            Id = 10,
                            AttendanceTakenAt = new DateTime(2025, 12, 9, 21, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 3,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2025, 12, 9, 21, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 3,
                            GroupId = 4,
                            Name = "week 2 - session 2",
                            RecordLink = "https://zoom.us/rec/10",
                            SessionDate = new DateTime(2025, 12, 9, 19, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2025, 12, 9, 19, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 3,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 5,
                            Type = "live"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = 1,
                            Name = "week 3 - session 1",
                            SessionDate = new DateTime(2025, 12, 13, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "pending",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "live"
                        },
                        new
                        {
                            Id = 12,
                            AttendanceTakenAt = new DateTime(2026, 5, 7, 20, 5, 0, 0, DateTimeKind.Utc),
                            AttendanceTakenById = 2,
                            CreatedAt = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndedAt = new DateTime(2026, 5, 7, 20, 0, 0, 0, DateTimeKind.Utc),
                            EndedById = 2,
                            GroupId = 1,
                            Name = "week 17 - session 2",
                            RecordLink = "https://zoom.us/rec/12",
                            SessionDate = new DateTime(2026, 5, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2026, 5, 7, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedById = 2,
                            Status = "finished",
                            Topic = "technical",
                            TrainerId = 1,
                            Type = "live"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.SessionAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("SessionAttachments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttachmentType = "pdf",
                            CreatedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileUrl = "https://drive.google.com/file/intro.pdf",
                            SessionId = 1,
                            Title = "Session 1 - introduction",
                            UploadedById = 2
                        });
                });

            modelBuilder.Entity("LMS.API.Models.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupId = 2,
                            JoinedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 9
                        },
                        new
                        {
                            Id = 2,
                            GroupId = 3,
                            JoinedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 10
                        },
                        new
                        {
                            Id = 3,
                            GroupId = 3,
                            JoinedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 11
                        },
                        new
                        {
                            Id = 4,
                            GroupId = 3,
                            JoinedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 12
                        },
                        new
                        {
                            Id = 5,
                            GroupId = 3,
                            JoinedAt = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 13
                        },
                        new
                        {
                            Id = 6,
                            GroupId = 1,
                            JoinedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 14
                        },
                        new
                        {
                            Id = 7,
                            GroupId = 1,
                            JoinedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 15
                        },
                        new
                        {
                            Id = 8,
                            GroupId = 1,
                            JoinedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 16
                        },
                        new
                        {
                            Id = 9,
                            GroupId = 4,
                            JoinedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 17
                        },
                        new
                        {
                            Id = 10,
                            GroupId = 4,
                            JoinedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = 18
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            SessionId = 1,
                            Title = "Session Feedback"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.SurveySubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveySubmissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feedback = "Great session!",
                            Rating = 4.5m,
                            StudentId = 14,
                            SubmittedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            SurveyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Feedback = "Good",
                            Rating = 4.0m,
                            StudentId = 15,
                            SubmittedAt = new DateTime(2025, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            SurveyId = 1
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamLeadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeamLeadId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LMS.API.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("LMS.API.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Description = "بسبب ظروف صحية والاب توب بانيظور مش هعرف اصلحه",
                            Status = "in_progress",
                            StudentId = 14,
                            Title = "انسحاب من المبادرة"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            Description = "أتقدم باعتذاري عن اكمال كورس المبادرة blender",
                            Status = "in_progress",
                            StudentId = 15,
                            Title = "أعتذار عن المبادرة"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 12, 23, 0, 0, 0, DateTimeKind.Utc),
                            Description = "I am unable to replace a previously submitted assignment with an updated version.",
                            Status = "in_progress",
                            StudentId = 16,
                            Title = "Assignment Submission System Error"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.TicketReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketReplies");
                });

            modelBuilder.Entity("LMS.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasFilter("[StudentCode] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lms.com",
                            IsActive = true,
                            Name = "System Admin",
                            PasswordHash = "$2a$11$.nzrka3F2S10Stz6YTE1.O/irrC/D.wzsH.MUz8K.3W5HCff2QVAi",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amr45409@gmail.com",
                            IsActive = true,
                            Name = "Amr Atef",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Phone = "01012345678",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.coord@lms.com",
                            IsActive = true,
                            Name = "Sara Mohamed",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Phone = "01098765432",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alaaelawady50@gmail.com",
                            IsActive = true,
                            Name = "Alaa Elawady",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "emad@lms.com",
                            IsActive = true,
                            Name = "Emad Eletreby",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "polakamal@hotmail.com",
                            IsActive = true,
                            Name = "Pola Zaki",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hatem.heshmat@gmail.com",
                            IsActive = true,
                            Name = "Hatem Heshmat",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mostafa@lms.com",
                            IsActive = true,
                            Name = "Mostafa Ayman",
                            PasswordHash = "$2a$11$2qGeXF8MhUbnOC3BgL4qA.Me0R8faRzhCxMDFWSsRtmc4LGoGygIW",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 9,
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "soha199922@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Soha Osama",
                            NationalId = "99901555459839",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "+201555459839",
                            Role = "Student",
                            StudentCode = "STU-0009"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seif23018449@gmail.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Saif Al Deen Mohamed",
                            NationalId = "30512202103877",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01006042020",
                            Role = "Student",
                            StudentCode = "STU-0010"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aya479360@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Aya Ezzat Mohamed",
                            NationalId = "30209171700745",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01096196775",
                            Role = "Student",
                            StudentCode = "STU-0011"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayatmohamed542@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Aya Mohamed Abd Elmotaal",
                            NationalId = "30407271700668",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01021309389",
                            Role = "Student",
                            StudentCode = "STU-0012"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mariamhany332004@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Mariam Hany Abdelmohseen",
                            NationalId = "30403031700746",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01158884919",
                            Role = "Student",
                            StudentCode = "STU-0013"
                        },
                        new
                        {
                            Id = 14,
                            City = "Alexandria",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.hassan@gmail.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Ahmed Hassan",
                            NationalId = "20001011234567",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01112345678",
                            Role = "Student",
                            StudentCode = "STU-0014"
                        },
                        new
                        {
                            Id = 15,
                            City = "Giza",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mohamed.ali@gmail.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Mohamed Ali",
                            NationalId = "20002021234568",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01223456789",
                            Role = "Student",
                            StudentCode = "STU-0015"
                        },
                        new
                        {
                            Id = 16,
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nour.ibrahim@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Nour Ibrahim",
                            NationalId = "20003031234569",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01534567890",
                            Role = "Student",
                            StudentCode = "STU-0016"
                        },
                        new
                        {
                            Id = 17,
                            City = "Cairo",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.khalid@gmail.com",
                            Gender = "Male",
                            IsActive = true,
                            Name = "Omar Khalid",
                            NationalId = "20004041234570",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01645678901",
                            Role = "Student",
                            StudentCode = "STU-0017"
                        },
                        new
                        {
                            Id = 18,
                            City = "Mansoura",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "fatma.youssef@gmail.com",
                            Gender = "Female",
                            IsActive = true,
                            Name = "Fatma Youssef",
                            NationalId = "20005051234571",
                            PasswordHash = "$2a$11$hr.7zd7ln87qSHBncG.1PuPN..XPt12MFkd2BIGYHSisnYEuW90le",
                            Phone = "01756789012",
                            Role = "Student",
                            StudentCode = "STU-0018"
                        });
                });

            modelBuilder.Entity("LMS.API.Models.Assignment", b =>
                {
                    b.HasOne("LMS.API.Models.Session", "Session")
                        .WithMany("Assignments")
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMS.API.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("LMS.API.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany("AssignmentSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.API.Models.Attendance", b =>
                {
                    b.HasOne("LMS.API.Models.Session", "Session")
                        .WithMany("Attendances")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.API.Models.CoordinatorGroup", b =>
                {
                    b.HasOne("LMS.API.Models.User", "Coordinator")
                        .WithMany("CoordinatorGroups")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.Group", "Group")
                        .WithMany("CoordinatorGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coordinator");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("LMS.API.Models.Quiz", b =>
                {
                    b.HasOne("LMS.API.Models.Session", "Session")
                        .WithMany("Quizzes")
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMS.API.Models.QuizQuestion", b =>
                {
                    b.HasOne("LMS.API.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("LMS.API.Models.QuizSubmission", b =>
                {
                    b.HasOne("LMS.API.Models.Quiz", "Quiz")
                        .WithMany("Submissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany("QuizSubmissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.API.Models.Session", b =>
                {
                    b.HasOne("LMS.API.Models.User", "AttendanceTakenBy")
                        .WithMany()
                        .HasForeignKey("AttendanceTakenById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS.API.Models.User", "EndedBy")
                        .WithMany()
                        .HasForeignKey("EndedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS.API.Models.Group", "Group")
                        .WithMany("Sessions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "StartedBy")
                        .WithMany()
                        .HasForeignKey("StartedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LMS.API.Models.Instructor", "Trainer")
                        .WithMany("TrainedSessions")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceTakenBy");

                    b.Navigation("EndedBy");

                    b.Navigation("Group");

                    b.Navigation("StartedBy");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("LMS.API.Models.SessionAttachment", b =>
                {
                    b.HasOne("LMS.API.Models.Session", "Session")
                        .WithMany("Attachments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LMS.API.Models.StudentGroup", b =>
                {
                    b.HasOne("LMS.API.Models.Group", "Group")
                        .WithMany("StudentGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany("StudentGroups")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.API.Models.Survey", b =>
                {
                    b.HasOne("LMS.API.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LMS.API.Models.SurveySubmission", b =>
                {
                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.Survey", "Survey")
                        .WithMany("Submissions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("LMS.API.Models.Team", b =>
                {
                    b.HasOne("LMS.API.Models.Group", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "TeamLead")
                        .WithMany()
                        .HasForeignKey("TeamLeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("TeamLead");
                });

            modelBuilder.Entity("LMS.API.Models.TeamMember", b =>
                {
                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LMS.API.Models.Ticket", b =>
                {
                    b.HasOne("LMS.API.Models.User", "Student")
                        .WithMany("Tickets")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LMS.API.Models.TicketReply", b =>
                {
                    b.HasOne("LMS.API.Models.Ticket", "Ticket")
                        .WithMany("Replies")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LMS.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LMS.API.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LMS.API.Models.Group", b =>
                {
                    b.Navigation("CoordinatorGroups");

                    b.Navigation("Sessions");

                    b.Navigation("StudentGroups");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("LMS.API.Models.Instructor", b =>
                {
                    b.Navigation("TrainedSessions");
                });

            modelBuilder.Entity("LMS.API.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LMS.API.Models.Session", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");

                    b.Navigation("Attendances");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("LMS.API.Models.Survey", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("LMS.API.Models.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("LMS.API.Models.Ticket", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("LMS.API.Models.User", b =>
                {
                    b.Navigation("AssignmentSubmissions");

                    b.Navigation("Attendances");

                    b.Navigation("CoordinatorGroups");

                    b.Navigation("QuizSubmissions");

                    b.Navigation("StudentGroups");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
